dist: xenial
sudo: false
language: ruby

rvm: 2.3.7

jobs:
  include:
    - stage: test for pry
      rvm: 2.4.1
      before_install:
      - bash travis/.travis_pry.sh
      install: skip
      before_script: skip
      script: echo No pry found
    - stage: test
      services:
      - mysql
      env: DB=mysql
      gemfile: Gemfile
      before_install:
      - mysql -e 'CREATE DATABASE test;'
    - env: DB=mysql57
      gemfile: Gemfile
      env: DB=mariadb
      gemfile: Gemfile
          - addons:
        mariadb: '10.0'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ghostscript
  - sudo apt-get install graphviz
  - sudo apt-get install qt5-default libqt5webkit5 gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  - qtchooser -qt=qt5
  - bash travis/.travis_setup.sh

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:fixtures:load FIXTURES_PATH=spec/fixtures

script:
  - xvfb-run bundle exec rspec

branches:
  only:
    - master
    - ui-design
    - development
    - fromthepage.com
    - indianapolis
